import type { DefaultTheme } from "vitepress";

// This file is auto-generated by scripts/generate-sidebar.mjs.
// Do not edit manually.
type SidebarItemWithCollapsible = Omit<DefaultTheme.SidebarItem, "items"> & {
	collapsible?: boolean;
	items?: SidebarItemWithCollapsible[];
};

export const sidebar: SidebarItemWithCollapsible[] = [
	{
		text: "Подготовка к интервью",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Подготовка к ML-собеседованию", link: "/interview-prep/podgotovka-k-ml-sobesedovaniyu" }
		],
	},
	{
		text: "Математика",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Вероятность и статистика", link: "/math/veroyatnost-i-statistika-dlya-ml" },
			{ text: "Линейная алгебра", link: "/math/lineynaya-algebra-dlya-ml" }
		],
	},
	{
		text: "Machine Learning",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Обучение без учителя", link: "/ml/obuchenie-bez-uchitelya" },
			{ text: "Обучение с учителем", link: "/ml/obuchenie-s-uchitelem" }
		],
	},
	{
		text: "Deep Learning",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Основы нейросетей", link: "/deep-learning/osnovy-neirosetei" },
			{ text: "Трансформеры база", link: "/deep-learning/transformery-baza" }
		],
	},
	{
		text: "MLOps",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Признаки и валидация", link: "/mlops/feature-engineering-i-validatsiya" },
			{ text: "Deploy и мониторинг", link: "/mlops/deploy-i-monitoring" }
		],
	},
	{
		text: "Python",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Обзор", link: "/python" },
			{
				text: "Язык Python",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Введение в Python", link: "/python/yazyk-python/vvedenie-v-python" },
					{ text: "Исключения и файлы", link: "/python/yazyk-python/isklyucheniya-context-managers-i-fayly" },
					{ text: "Итераторы и генераторы", link: "/python/yazyk-python/iteratory-generatory-i-comprehensions" },
					{ text: "Typing для ML", link: "/python/yazyk-python/typing-dlya-python-i-ml" },
					{ text: "Datetime и timezone", link: "/python/yazyk-python/datetime-i-timezone" },
					{
						text: "Core",
						collapsible: true,
						collapsed: true,
						items: [
							{ text: "Core обзор", link: "/python/yazyk-python/1-core/python-core-funktsii-klassy-moduli-venv-i-pip" },
							{ text: "Синтаксис и переменные", link: "/python/yazyk-python/1-core/osnovy-sintaksisa-i-peremennye" },
							{ text: "Основные функции", link: "/python/yazyk-python/1-core/osnovnye-funktsii" },
							{ text: "Арифметические операторы", link: "/python/yazyk-python/1-core/arifmeticheskie-operatory" },
							{ text: "Операторы сравнения", link: "/python/yazyk-python/1-core/operatory-sravneniya" },
							{ text: "Boolean и условия", link: "/python/yazyk-python/1-core/boolean-i-usloviya" },
							{ text: "Функции", link: "/python/yazyk-python/1-core/funktsii-v-python" },
							{ text: "Классы", link: "/python/yazyk-python/1-core/klassy-v-python" },
							{ text: "Модули и окружение", link: "/python/yazyk-python/1-core/moduli-venv-i-pip" },
							{ text: "Логические и побитовые", link: "/python/yazyk-python/1-core/logicheskie-i-pobitovye-operatory" }
						],
					},
					{
						text: "Типы данных",
						collapsible: true,
						collapsed: true,
						items: [
							{ text: "Типы главная", link: "/python/yazyk-python/tipy-dannykh/tipy-glavnaya" },
							{ text: "Операции со строками", link: "/python/yazyk-python/tipy-dannykh/operatsii-so-strokami" },
							{ text: "Списки базовые операции", link: "/python/yazyk-python/tipy-dannykh/spiski-bazovye-operatsii" },
							{ text: "Изменяемые типы", link: "/python/yazyk-python/tipy-dannykh/izmenyaemye-tipy" },
							{ text: "Методы типов данных", link: "/python/yazyk-python/tipy-dannykh/metody-tipov-dannykh" },
							{ text: "Неизменяемые типы", link: "/python/yazyk-python/tipy-dannykh/neizmenyaemye-tipy" }
						],
					}
				],
			},
			{
				text: "Экосистема Python",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Загрузка данных", link: "/python/ekosistema-python/zagruzka-dannykh-i-formaty" },
					{ text: "SQL из Python", link: "/python/ekosistema-python/sql-iz-python" },
					{ text: "NumPy и Pandas", link: "/python/ekosistema-python/numpy-i-pandas-dlya-ml" },
					{ text: "EDA и визуализация", link: "/python/ekosistema-python/eda-i-vizualizatsiya" },
					{ text: "Scikit-learn и pipeline", link: "/python/ekosistema-python/scikit-learn-i-pipeline" },
					{ text: "Продвинутый preprocessing", link: "/python/ekosistema-python/prodvinutyy-preprocessing" },
					{ text: "Воспроизводимость ML-кода", link: "/python/ekosistema-python/vosproizvodimost-ml-koda" },
					{ text: "Logging и CLI", link: "/python/ekosistema-python/logging-i-cli-dlya-ml-skriptov" },
					{ text: "Jupyter workflow", link: "/python/ekosistema-python/jupyter-workflow" },
					{ text: "Experiment tracking", link: "/python/ekosistema-python/experiment-tracking" },
					{ text: "Артефакты и inference", link: "/python/ekosistema-python/artefakty-modeli-i-inference" },
					{ text: "Тестирование и валидация", link: "/python/ekosistema-python/testirovanie-i-validatsiya-dannykh" },
					{ text: "PyTorch basics", link: "/python/ekosistema-python/pytorch-basics" }
				],
			}
		],
	}
];
