import type { DefaultTheme } from "vitepress";

// This file is auto-generated by scripts/generate-sidebar.mjs.
// Do not edit manually.
type SidebarItemWithCollapsible = Omit<DefaultTheme.SidebarItem, "items"> & {
	collapsible?: boolean;
	items?: SidebarItemWithCollapsible[];
};

export const sidebar: SidebarItemWithCollapsible[] = [
	{
		text: "Подготовка к интервью",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Подготовка к ML-собеседованию", link: "/interview-prep/podgotovka-k-ml-sobesedovaniyu" }
		],
	},
	{
		text: "Математика",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Вероятность и статистика", link: "/math/veroyatnost-i-statistika-dlya-ml" },
			{ text: "Линейная алгебра для", link: "/math/lineynaya-algebra-dlya-ml" }
		],
	},
	{
		text: "Machine Learning",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Обучение без учителя", link: "/ml/obuchenie-bez-uchitelya" },
			{ text: "Обучение с учителем", link: "/ml/obuchenie-s-uchitelem" }
		],
	},
	{
		text: "Deep Learning",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Основы нейросетей", link: "/deep-learning/osnovy-neirosetei" },
			{ text: "Трансформеры база", link: "/deep-learning/transformery-baza" }
		],
	},
	{
		text: "MLOps",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Deploy и мониторинг", link: "/mlops/deploy-i-monitoring" },
			{ text: "Feature engineering и", link: "/mlops/feature-engineering-i-validatsiya" }
		],
	},
	{
		text: "Python",
		collapsible: true,
		collapsed: true,
		items: [
			{ text: "Введение в Python", link: "/python/vvedenie-v-python" },
			{ text: "NumPy и Pandas", link: "/python/numpy-i-pandas-dlya-ml" },
			{
				text: "1 Core",
				collapsible: true,
				collapsed: true,
				items: [
					{ text: "Логические и побитовые", link: "/python/1-core/logicheskie-i-pobitovye-operatory" },
					{ text: "Функции классы модули", link: "/python/1-core/python-core-funktsii-klassy-moduli-venv-i-pip" },
					{
						text: "Типы данных",
						collapsible: true,
						collapsed: true,
						items: [
							{ text: "Общая информация", link: "/python/1-core/tipy-dannykh/obshaya-informatsiya" },
							{ text: "Изменяемые типы", link: "/python/1-core/tipy-dannykh/izmenyaemye-tipy" },
							{ text: "Неизменяемые типы", link: "/python/1-core/tipy-dannykh/neizmenyaemye-tipy" }
						],
					}
				],
			}
		],
	}
];
